% ///	Copyright(c) 2017 United States Government as represented by the 
% ///	Administrator for The National Aeronautics and Space Administration.  
% ///	All Rights Reserved. 
% ///	
% ///		Government Agency: NASA 
% ///		Government Agency Original Software Designation: GSC-18375-1
% ///		Government Agency Original Software Title: Second Generation Beacon Performance Analysis Test Tools
% ///		User Registration Requested.  Please Visit https://software.nasa.gov/
% ///     
% ///     Module: compilespecs 
% ///     
% ///     Author:   Reese Bovard
% ///             Concentric Real Time, LLC
% ///   
% ///     [version]:	$Revision: 11 $ $Date: 2019-09-23 09:10:04 -0400 (Mon, 23 Sep 2019) $
% ///				$Id: compilespecs.m 11 2019-09-23 13:10:04Z reesebo $
% ///            

function compilespecs(tab, specs, xlsfile)



writetablersb(tab,xlsfile);
rownames={  'Mode', ...
            'Message (hex)', ...
            'PN I', ...
            'PN I Errors', ...
            'PN Q', ...
            'PN Q Errors', ...
            'Chiprate Preamble(chips/s)', ...
            'Chiprate Variation Over Preamble(chips/s^2)', ...
            'Chiprate Over Message (chip/s)', ...
            'Chiprate Variation (chips/s^2)', ...
            'Long Term Carrier Stability (ppm)', ...
            'Short Term Carrier Stability (ppb) (max)', ...
            'EVM (rms) max', ...
            'IQOffset (% chip)'};
        
xlswrite(xlsfile, rownames', 'Measure', 'A1');

content = { specs.mode, ...
            ['x.' specs.ms.hex], ...
            ['x.' specs.pn.i ], ...
            specs.pn.ierr, ...
            ['x.' specs.pn.q], ...
            specs.pn.qerr, ...
            specs.cr, ...
            specs.crvec.variation.pre, ...
            specs.crvec.all, ...
            specs.crvec.variation.all, ...
            specs.sq.offset/406.05, ...
            specs.sq.dev, ...
            max(specs.evm), ...
            specs.iqoffset
            };
        
for(ix=1:length(rownames))
    if(ischar(content{ix}))
        o=content(ix);
    else
        o=content{ix};
    end
    xlswrite(xlsfile, o, 'Measure', sprintf('B%d', ix));
end

removesheets(xlsfile);                

