function Hd = mf2(fs,sps)
%MF2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 31-Jan-2018 20:24:12

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in Hz.
if(isempty(fs))
    Fs = 384000;  % Sampling Frequency
else
    Fs=fs;
end

N    = 64;         % Order
Fc   = 35000;      % Cutoff Frequency
TM   = 'Rolloff';  % Transition Mode
R    = 0.2;        % Rolloff
DT   = 'sqrt';     % Design Type
Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
