function Hd = mf3(fs)
%MF3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 29-Jan-2019 17:32:20

% FIR Window Raised-cosine filter designed using the FIRRCOS function.
if(isempty(fs))
    Fs = 384000;  % Sampling Frequency
else
    Fs=fs;
end
% All frequency values are in Hz.

N    = 64;         % Order
Fc   = 38400;      % Cutoff Frequency
TM   = 'Rolloff';  % Transition Mode
R    = 0.8;        % Rolloff
DT   = 'sqrt';     % Design Type
Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
