function Hd = mfp8(Fs,sps)
%MF00 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 15-Oct-2019 07:56:00

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in Hz.
%Fs = 384000;  % Sampling Frequency

N    = sps;         % Order
Fc   = 38400;      % Cutoff Frequency
TM   = 'Rolloff';  % Transition Mode
R    = 0.8;       % Rolloff
DT   = 'sqrt';     % Design Type
Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
